karionCourseBundleAdmin_create:
    pattern:  /create
    defaults: { _controller: karionCourseBundle:Admin:create }
    
karionCourseBundleAdmin_edit:
    pattern:  /edit/{id}
    defaults: { _controller: karionCourseBundle:Admin:edit } 
    requirements: 
      id: \d+ 

karionCourseBundleAdmin_enable:
    pattern:  /enable/{id}
    defaults: { _controller: karionCourseBundle:Admin:enable } 
    requirements: 
      _method: POST
      id: \d+ 
      
karionCourseBundleAdmin_list:
    pattern:  /list
    defaults: { _controller: karionCourseBundle:Admin:list }      
      
