karionCourseBundle_homepage:
    pattern:  /
    defaults: { _controller: karionCourseBundle:Course:list }
    requirements:
      _method: GET
    
karionCourseBundle_courseShow:
    pattern:  /course/{id}
    defaults: { _controller: karionCourseBundle:Course:show } 
    requirements: 
      _method: GET 
      id: \d+ 

#admin       
karionCourseBundleAdmin:
  resource: "@karionCourseBundle/Resources/config/routing_admin.yml"
  prefix:   /admin/course