karionCourseBundle_homepage:
    pattern:  /
    defaults: { _controller: karionCourseBundle:Course:list }
    requirements:
      _method: GET
    
karionCourseBundle_courseShow:
    pattern:  /course/{id}
    defaults: { _controller: karionCourseBundle:Course:show } 
    requirements: 
      _method: GET 
      id: \d+ 
