karionLessonBundle:
    resource: "@karionLessonBundle/Resources/config/routing.yml"
    prefix:   /

karionCourseBundle:
    resource: "@karionCourseBundle/Resources/config/routing.yml"
    prefix:   /

#user and security bundle
karionUserBundle:
    resource: "@karionUserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
