security:
   
    encoders:
      karion\UserBundle\Entity\User:
        algorithm:        sha512
        encode_as_base64: false
        iterations:       1

#        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_USER, ROLE_CREATOR, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: karionUserBundle:User }
#            entity: { class: karionUserBundle:User, property: username }
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        normal:    
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                
            logout:
                path:   /logout
                target: /
#        admin_area:
#            pattern:    ^/admin
#            http_basic: ~

#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#        login:
#            pattern:  ^/demo/secured/login$
#            security: false

#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: /demo/secured/login_check
#                login_path: /demo/secured/login
#            logout:
#                path:   /demo/secured/logout
#                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    acl:
        connection: default
        
    access_control:
#        - { path: ^/admin/course/create, roles: ROLE_CREATOR }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
