<?php

namespace karion\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
  const ROLE_USER = 'ROLE_USER';
  const ROLE_CREATOR = 'ROLE_CREATOR';
  const ROLE_ADMIN = 'ROLE_ADMIN';
  const ROLE_ALLOWED_TO_SWITCH = 'ROLE_ALLOWED_TO_SWITCH';
  
  
  public function getRole($name)
  {
   
    $q = $this
      ->createQueryBuilder('g')
      ->where('g.role = :role')
      ->setParameter('role', $name)
      ->getQuery()
    ;
    
    try
    {
      $role = $q->getSingleResult();
    }
    catch (NoResultException $e)
    {
      throw new Exception('No role find', null, 0, $e);
    }

    return $role;
  }
  
}