<?php

namespace karion\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTokenRepository extends EntityRepository
{
  public function findOneActiveByToken($token)
  {
   
    $a = $this->createQueryBuilder('ut')
    ->where('ut.token = :token')
    ->setParameter('token', $token )
    ->andWhere('ut.activeTo > :now')
    ->setParameter('now', new \DateTime("now") )
    ->getQuery()

    ->getSingleResult();

    return $a;
    
    
  }
}