login:
  pattern:  /login
  defaults: { _controller: karionUserBundle:Login:login }
    
login_check:
  pattern: /login_check

logout:
  pattern: /logout
  
#user routing
user:
  resource: "@karionUserBundle/Resources/config/routing_user.yml"
  prefix:   /user

