parameters:
#    karion_user.example.class: karion\UserBundle\Example

services:
#    karion_user.example:
#        class: %karion_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
