karion\UserBundle\Entity\Group:
  type: entity
  table: group_my
  repositoryClass: karion\UserBundle\Entity\GroupRepository 
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 40
      
    role:  
      type: string
      length: 20
      unique: true
      
  manyToMany:
    users:
      targetEntity: karion\UserBundle\Entity\User
      mappedBy: groups    
    #ManyToMany(targetEntity="User", mappedBy="groups")
