<?php

namespace karion\LessonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends EntityRepository
{
  public function getLessonWithCourse($id)
  {
      $a = $this->createQueryBuilder('l')
        ->select('c, l')
        ->innerJoin('l.course', 'c')
        ->where('l.id = :id')
        ->setParameter('id', $id )
        ->getQuery()
      
        ->getSingleResult();
    
    
    return $a;
  }
  
    public function getLessonWithCourseBySlug($courseId, $slug)
    {
      $a = $this->createQueryBuilder('l')
        ->select('c, l')
        ->innerJoin('l.course', 'c')
        ->where('c.id = :id')
        ->andWhere('l.slug = :slug')
        ->setParameter('id', $courseId )
        ->setParameter('slug', $slug )
        ->getQuery()
      
        ->getSingleResult();
    
    return $a;
  }
}