parameters:
#    karion_lesson.example.class: karion\LessonBundle\Example

services:
#    karion_lesson.example:
#        class: %karion_lesson.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
